# Generated by Django 5.1 on 2024-08-27 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devolver', '0001_initial'),
        ('emprestimo', '0009_remove_emprestar_livro_emprestar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolver',
            name='emprestimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emprestimo.emprestimo'),
        ),
    ]
