# Generated by Django 5.1 on 2024-08-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolver', '0002_initial'),
        ('emprestimo', '0009_remove_emprestar_livro_emprestar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolver',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='devolver',
            name='emprestimo_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emprestimo.emprestimo'),
        ),
    ]
