# Generated by Django 5.1 on 2024-08-27 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolver', '0003_remove_devolver_emprestimo_devolver_emprestimo_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolver',
            name='data_devolvido',
        ),
        migrations.AddField(
            model_name='devolver',
            name='data_devolucao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
