# Generated by Django 5.1 on 2024-08-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0002_devolucao_data_devolvido_devolucao_entrega_atrasada_and_more'),
        ('livro', '0005_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='livro_devolver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livro'),
        ),
    ]
