# Generated by Django 5.1 on 2024-08-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0003_devolucao_livro_devolver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='duracao',
            field=models.IntegerField(default=3),
        ),
    ]
