# Generated by Django 5.1 on 2024-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_livro_autor_livro_categoria_livro_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
        ),
    ]
