# Generated by Django 5.1 on 2024-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_livro_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, default='Aqui vai uma breve descrição sobre a historia do livro,falando sobre quem é o personagem principal, qual a suahistoria, o que vamos encontrar e entao deixar no ar oque so podemos saber se ler-mos. este texto ajuda ousuario a decidir se tem interesse ou nao em ler esselivro ou se ele contem as informacoes que precisa.', max_length=500, null=True),
        ),
    ]
