# Generated by Django 5.1 on 2024-08-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
    ]
