# Generated by Django 5.1 on 2024-08-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_options_remove_usuario_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='numero',
            new_name='telefone',
        ),
    ]
