# Generated by Django 5.1 on 2024-08-23 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_emprestimo_livro_emprestar'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolvido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='entrega_atrasada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='taxa',
            field=models.CharField(default='R$0,00', max_length=8),
        ),
    ]
