# Generated by Django 5.1 on 2024-08-27 00:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0008_rename_data_devolvido_devolver_data_final_and_more'),
        ('livro', '0006_remove_livro_nome_livro_titulo'),
        ('usuario', '0009_rename_numero_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestar',
            name='livro_emprestar',
        ),
        migrations.RemoveField(
            model_name='emprestar',
            name='nome_estudante',
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('data_devolvido', models.DateTimeField(blank=True, null=True)),
                ('entrega_atrasada', models.BooleanField(default=False)),
                ('taxa', models.CharField(default='R$0,00', max_length=8)),
                ('livro_emprestar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livro')),
                ('nome_estudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Devolver',
        ),
        migrations.DeleteModel(
            name='Emprestar',
        ),
    ]
