# Generated by Django 5.1 on 2024-08-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0009_remove_emprestar_livro_emprestar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolvido',
        ),
    ]
